---
title: "Spectral Decomposition"
author: "Nicholas Baetge"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
output: github_document
---

```{r load packages, message=FALSE, warning=FALSE, wrapper = TRUE}
library(tidyverse)
library(patchwork)
library(lubridate)
library(patchwork)
```

- 

#############

# IMPORT DATA

############## 


```{r read data, message=FALSE, warning=FALSE, wrapper = TRUE}
pf <- read_csv("~/Box Sync/Phyto_bbp/DATA/FINAL/diel_optics_phyto_cultures/analyses/final_data/PAR.csv")
sf <- read_csv("~/Box Sync/Phyto_bbp/DATA/FINAL/diel_optics_phyto_cultures/analyses/final_data/FINAL_SUMMARY_11102023.csv")
```

#############

# SPECTRAL DECOMPOSITION

############## 

This is done using the MATLAB script "SpecDecomp.m" 
-files needed are unsmoothACS.m, FitSpectra_HM2.m, and GaussDecomp.m

```{r export data to matlab, message=FALSE, warning=FALSE, wrapper = TRUE}
matlab <- sf %>% 
  select(exp, tp, wl, mean_ap, sd_ap) %>% 
  drop_na(mean_ap) 

matlab %>%  group_by(exp) %>%
  group_walk( ~ write_csv(.x, paste0(.y$exp, ".csv")))
```

#############

# IMPORT AND WRANGLE DECOMPOSED SPECTRA

############## 

```{r define wls and gaussians}
wavelengths <- matlab %>% select(wl) %>% distinct() %>% drop_na()
wl <- wavelengths$wl
gaus_peaks <- c("non-pigmented", 406,434,453,470,492,523,550,584,617,638,660,675)
```

-

```{r import matlab files, message=FALSE, warning=FALSE}
order <- matlab %>% select(exp, tp) %>% distinct() %>% arrange(factor(exp, levels = c("OL22-2", "OL22-3", "SYN22-4", "SYN22-5", "TP22-14")))
meta <- sf %>% select(exp:plot_datetime, mean_chl_line_height) %>% filter(source == "Optics") %>% distinct()

amps_files <-
  fs::dir_ls(path = "decomposed/", regexp = "amps\\.csv$")

amps <- amps_files %>%
  purrr::map_dfr(read.csv,
                 skip = 1,
                 header = F,
                 .id = "source") %>% 
  rename_all( ~ c("exp", gaus_peaks)) %>% 
  mutate(exp = gsub("_amps.csv", "", exp),
         exp = gsub("decomposed/", "", exp)) %>% 
   bind_cols(., order %>% select(tp)) %>%
  rename(exp = 1) %>% 
  select(exp, tp, everything()) %>% 
  select(1:15) %>% 
  mutate(ppc_chla = `492`/`675`,
         psc_chla = `523`/`675`,
         pub_peb = `492`/`550`,
         pe_chla = (`550` + `492`)/`675`,
         chlb_chla = `470`/`675`
         ) %>%
  pivot_longer(., 3:20, names_to = "spectra", values_to = "peak") %>% 
  distinct() %>% 
  left_join(., meta) %>% 
  select(exp, exp_no:source, tp, datetime:plot_datetime, mean_chl_line_height, spectra, peak) %>%
  mutate(spectra_label = ifelse(spectra == "non-pigmented", "Non-pigmented", spectra),
         spectra_label = ifelse(spectra == "ppc_chla", "paste('PPC:', 'Chl-', italic('a'), ' (492:675 nm)')", spectra_label),
         spectra_label = ifelse(spectra == "psc_chla", "paste('PSC:', 'Chl-', italic('a'), ' (523:675 nm)')", spectra_label),
         spectra_label = ifelse(spectra == "pub_peb", "paste('PUB:PEB (492:550 nm)')", spectra_label),
         spectra_label = ifelse(spectra == "pe_chla", "paste('PE:', 'Chl ', italic('a'), ' ([492 + 550]:675 nm)')", spectra_label),
         spectra_label = ifelse(spectra == "chlb_chla", "paste('Chl-', italic('b:'), 'Chl-', italic('a'), ' (470:675 nm)')", spectra_label), .after = spectra)

unsmoothed_files <-
  fs::dir_ls(path = "decomposed/", regexp = "unsmoothed\\.csv$")

unsmoothed <- unsmoothed_files %>%
  purrr::map_dfr(read.csv,
                 skip = 1,
                 header = F,
                 .id = "source") %>% 
  rename_all( ~ c("exp", wl)) %>% 
  mutate(exp = gsub("_unsmoothed.csv", "", exp),
         exp = gsub("decomposed/", "", exp)) %>% 
  bind_cols(., order %>% select(tp)) %>%
  rename(exp = 1) %>% 
  select(exp, tp, everything()) %>% 
  select(1:85)

sumspec_files <-
  fs::dir_ls(path = "decomposed/", regexp = "sumspec\\.csv$")

sumspec <- sumspec_files %>%
  purrr::map_dfr(read.csv,
                 skip = 1,
                 header = F,
                 .id = "source") %>% 
  rename_all( ~ c("exp", wl)) %>% 
  mutate(exp = gsub("_sumspec.csv", "", exp),
         exp = gsub("decomposed/", "", exp)) %>% 
   bind_cols(., order %>% select(tp)) %>%
  rename(exp = 1) %>% 
  select(exp, tp, everything()) %>% 
  select(1:85)

compspec_files <-
  fs::dir_ls(path = "decomposed/", regexp = "compspec.*\\.csv")

compspec <- compspec_files  %>% 
   purrr::map_dfr(read.csv,
                 skip = 0,
                 header = F,
                 .id = "source") %>% 
  rename_all( ~ c("source", gaus_peaks)) %>% 
  mutate(source = gsub("decomposed/", "", source),
         source = gsub(".csv", "", source),
         source = gsub("compspec", "", source)) %>% 
  separate(source, into = c("exp", "tp"), sep = "_") %>% 
  group_by(exp, tp) %>% 
  mutate(wl = c(wl), .after = "tp") %>% 
  ungroup() %>% 
  mutate_at(vars(wl, tp), as.numeric)

```

-

```{r combine summed spectra and gaussians, message=FALSE, warning=FALSE}
to_combine_us <- unsmoothed %>% 
  pivot_longer(., 3:85, names_to = "wl", values_to = "unsmooth") %>% 
  mutate_at(vars(wl), as.numeric) %>% 
  distinct()

to_combine_ss <- sumspec %>% 
  pivot_longer(., 3:85, names_to = "wl", values_to = "sumspec") %>% 
  mutate_at(vars(wl), as.numeric) %>% 
  distinct()

combined <- compspec %>% 
  left_join(., to_combine_us) %>% 
  left_join(., to_combine_ss) %>% 
  pivot_longer(., 4:18, names_to = "spectra", values_to = "ap") %>% 
  left_join(., meta) %>% 
  select(exp, exp_no:source, tp, datetime:mean_chl_line_height, wl:ap) %>%
  mutate(spectra_label = ifelse(spectra == "non-pigmented", "Non-pigmented", spectra),
         spectra_label = ifelse(spectra == "unsmooth", "Unsmoothed", spectra_label),
         spectra_label = ifelse(spectra == "sumspec", "Summed Gaussians", spectra_label), .after = spectra) %>% 
  left_join(., matlab %>% select(exp:wl, sd_ap) %>% distinct()) %>% 
  mutate(sd_ap = ifelse(!spectra == "unsmooth", NA, sd_ap)) %>% 
  arrange(datetime)

```
########################### 

# SAVE DATA

########################### 

```{r save data, wrapper=TRUE}
write_csv(combined, "~/Box Sync/Phyto_bbp/DATA/FINAL/diel_optics_phyto_cultures/final_data/Gaussian_Decompositions.csv")
write_csv(amps, "~/Box Sync/Phyto_bbp/DATA/FINAL/diel_optics_phyto_cultures/final_data/Pigment_Ratios.csv")
```





