---
title: "Plots by parameter"
author: "Nicholas Baetge"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
output: github_document
---

```{r chunk wrapper, include = FALSE}
knitr::knit_hooks$set(
  wrapper = function(before, options) {
    # the original chunk might be indented
    if (is.null(indent <- options$indent))
      indent <- ''
    
    # hide the wrapper=TRUE option
    opts <- gsub(', wrapper=TRUE', '', options$params.src)
    
    if (before) {
      # add the header
      sprintf('\n\n%s````\n```{r,%s}\n````\n', indent, opts)
    } else {
      # add the footer
      sprintf('\n\n%s````\n```\n````\n', indent)
    }
  }
)
```

- 

```{r load packages, message=FALSE, warning=FALSE, wrapper = TRUE}
library(tidyverse)
library(patchwork)
library(lubridate)
```

- 

#############

# IMPORT DATA

############## 


```{r read data, message=FALSE, warning=FALSE, wrapper = TRUE}
bf <- read_csv("FINAL_BOTTLE.csv")
sf <- read_csv("FINAL_SUMMARY.csv")
gaus <- read_csv("Gaussian_Decompositions.csv")
pigs <- read_csv("Pigment_Ratios.csv")
pf <- read_csv("PAR.csv") %>% 
  mutate(col = "Col",
         row = "Row")

pf2 <- bind_rows(pf, pf %>% mutate(col = "Col2", row = "Row")) %>% 
  rename(plot_datetime = new_datetime) 
```

-

```{r define night and day, message=FALSE, warning=FALSE, wrapper = TRUE}
shade <-
   tibble(
    dusk = seq.POSIXt(
      ymd_hms("2022-11-25 21:00:00"),
      by = 'day',
      length.out = 5
    ),
    dawn = seq.POSIXt(
      ymd_hms("2022-11-26 09:00:00"),
      by = "day",
      length.out = 5
    ),
    top = Inf,
    bottom = -Inf
  )

shade.pre <-
  tibble(
    dusk = seq.POSIXt(
      ymd_hms("2022-11-27 06:00:00"),
      by = 'day',
      length.out = 1
    ),
    dawn = seq.POSIXt(
      ymd_hms("2022-11-27 09:00:00"),
      by = "day",
      length.out = 1
    ),
    top = Inf,
    bottom = -Inf
  )



shade.log <-
  tibble(
    dusk = seq.POSIXt(
      ymd_hms("2022-11-26 21:00:00"),
      by = 'day',
      length.out = 3
    ),
    dawn = seq.POSIXt(
      ymd_hms("2022-11-27 09:00:00"),
      by = "day",
      length.out = 3
    ),
    top = Inf,
    bottom = 0
  )

shade.pre.log <-
  tibble(
    dusk = seq.POSIXt(
      ymd_hms("2022-11-27 06:00:00"),
      by = 'day',
      length.out = 1
    ),
    dawn = seq.POSIXt(
      ymd_hms("2022-11-27 09:00:00"),
      by = "day",
      length.out = 1
    ),
    top = Inf,
    bottom = 0
  )
```

#############

# AESTHETICS

############## 

```{r custom theme for plots, wrapper = TRUE}
custom.theme <- theme(
  legend.position = "bottom",
  legend.title = element_text(size = 23),
  legend.key.size = unit(0.7, "cm"),
  legend.text = element_text(size = 23),
  axis.title = element_text(size = 23, face = "bold"),
  panel.spacing.x = unit(2, "cm"),
  strip.text.x = element_text(size = 23, color = "black", face = "bold"),
  strip.text.y = element_text(size = 23, color = "black", face = "bold"),
  strip.background = element_rect(
    color = "black",
    fill = alpha('light grey', 0.4),
    linewidth = 1.5,
    linetype = "solid"
  )
)
```

-

```{r color designations for phytoplankton, wrapper = TRUE}
phyto.colors <-
  c(
    "italic('O. lucimarinus')" = "#3B9AB2",
    "italic('T. pseudonana')" = "#E1AF00",
    "italic('Synechococcus ') (WH8102)" = "#F21A00"
  )

#alternate color for TP = "#e2c77c"

ac3.colors <-
  c(
    "440" = "#0000ff",
    "540" = "#81ff00",
    "660" = "#ff0000"
  )

bb3.colors <-
  c(
    "470" = "#00a9ff",
    "532" = "#65ff00",
    "660" = "#ff0000"
  )


gaus.colors <- c(
  "406" = "#8100cc",
  "434" = "#2800ff",
  "453" = "#0057ff",
  "470" = "#00a9ff",
  "492" = "#00ffea",
  "523" = "#42ff00",
  "550" = "#a3ff00",
  "584" = "#fff200",
  "617" = "#ff8200",
  "638" = "#ff2b00",
  "660" = "#ff0000",
  "675" = "#ff0000",
  "Non-pigmented" = "#964B00",
  "Unsmoothed" = "#000000",
  "Summed Gaussians" = "#BF40BF"
)


pig.colors <- c(
  "paste('PSC:', 'Chl-', italic('a'), ' (523:675 nm)')" = "#0057ff",
  "paste('PUB:PEB (492:550 nm)')" = "#42ff00",
  "paste('PE:', 'Chl-', italic('a'), ' (550:675 nm)')" = "#ff8200",
  "paste('PPC:', 'Chl-', italic('a'), ' ([492+550]:675 nm)')" = "#ff0000",
  "paste('Chl-', italic('b:'), 'Chl-', italic('a'), ' (470:675 nm)')" = "#000000"
)
```

#############

# PAR

############## 

```{r par plot, wrapper = TRUE}
par <- ggplot() +
  geom_rect(
    data = shade.log,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_rect(
    data = shade.pre.log,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_line(
    data = pf2,
    aes(x = plot_datetime,
        y = par),
    alpha = 0.7,
    linewidth = 1
  ) +
  labs(x = "",
       y = expression(bold(PAR ~ (µE ~ m ^ -2 ~ s ^ -1))),
       tag = "a") +
  guides(color = "none") +
  theme_linedraw(18) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  theme_linedraw(21) +
  custom.theme 


```


########################### 

# FCM

########################### 

```{r subset abund data, message=FALSE, warning=FALSE, wrapper = TRUE}
abund_data <- sf %>% 
  select(exp, exp_no, phyto, source, tp, plot_datetime, mean_cells, sd_cells) %>% 
  distinct() %>% 
  filter(!exp == "OL22-3" | !tp == 4) %>% 
  mutate_at(vars(mean_cells, sd_cells), ~ . * 1E6) %>% 
  mutate(source = case_when(source == "Culture" ~ "Directly~from~culture",
                            source == "Optics" ~ "Diluted~'in'~optical~sampling~system"))
```

-

```{r 1-cells plot, fig.width=16, fig.asp=1.4, message=FALSE, warning=FALSE, wrapper = TRUE}
scientific_10 <- function(x) {
  parse(text=gsub("e\\+*", " %*% 10^", scales::scientific_format()(x)))
}

scales <- list(scale_y_continuous(limits = c(3.5E11, 8E11), labels = scientific_10),
               scale_y_continuous(limits = c(5E9, 1.5E10), labels = scientific_10),
               scale_y_continuous(limits = c(5E12, 3E13), labels = scientific_10),
               scale_y_continuous(limits = c(2E10, 2E11), labels = scientific_10),
               scale_y_continuous(limits = c(3E13, 1.1E14), labels = scientific_10),
               scale_y_continuous(limits = c(2E11, 1.5E12), labels = scientific_10)
              
   )

cells <-  ggplot( data = abund_data[!is.na(abund_data$mean_cells),]) +
  geom_rect(
    data = shade.log,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
   geom_rect(
    data = shade.pre.log,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_errorbar(
    aes(
      x = plot_datetime,
      y = mean_cells,
      ymin = mean_cells - sd_cells,
      ymax = mean_cells + sd_cells,
      color = factor(phyto, levels = unique(abund_data$phyto)),
      group = interaction(phyto, source, exp_no)
    ),
    width = 2000,
    alpha = 0.7
  ) +
  geom_line(
    aes(
      x = plot_datetime,
      y = mean_cells,
      color = factor(phyto, levels = unique(abund_data$phyto)),
      linetype = as.character(exp_no),
      group = interaction(phyto, source, exp_no)
    ),
    size = 1,
    alpha = 0.7
  ) +
  geom_point(
    aes(
      x = plot_datetime,
      y = mean_cells,
      fill = factor(phyto, levels = unique(abund_data$phyto)),
      group = interaction(phyto, source, exp_no)
    ),
    color = "black",
    size = 4,
    shape = 21
  ) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  scale_shape_manual(values = c(21, 22)) +
  scale_color_manual(values = phyto.colors) +
  scale_fill_manual(values = phyto.colors, labels = scales::parse_format()) +
  labs(
    x = "Hour",
    y = expression(bold(Cell ~ abundance ~ (m^-3))),
    shape = "",
    fill = "",
    linetype = expression(bold(Experiment)),
    tag = "b"
  ) +
  guides(color = "none", fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(21) +
  ggh4x::facet_grid2(factor(phyto, levels = unique(abund_data$phyto))~factor(source, levels = unique(abund_data$source)),
             scales = "free_y",
             independent = "y",
             labeller = label_parsed) +
  ggh4x::facetted_pos_scales(y = scales) +
  custom.theme  +
   theme(
  strip.text.y = element_blank(),
  axis.text.y.right = element_blank(),
        axis.ticks.y.right = element_blank(),
        axis.line.y.right = element_blank() )

par.plot <- par + 
  ggh4x::facet_grid2(row~col,
             scales = "free_y",
             independent = "y") +
  # scale_y_continuous(labels = scientific_10) +
   theme(
  strip.text.y = element_blank(),
  strip.text.x = element_blank(),
  panel.spacing.x = unit(7.8, "lines")) 


par.plot / cells + 
  plot_layout(guides = "collect", heights = c(0.75,2))  &
  theme(legend.position = "bottom",
        legend.box="vertical",
        plot.tag = element_text(face = "bold"))
```

- 

```{r subset fcm data, message=FALSE, warning=FALSE, wrapper = TRUE}

fcm_data <- sf %>% 
  select(exp, exp_no, phyto, source, tp, plot_datetime, mean_fsc, mean_ssc, mean_red, mean_yel) %>% 
  distinct() %>% 
  rename_with(~str_remove(., 'mean_')) %>% 
  filter(!exp == "OL22-3" | !tp == 4) %>% 
  filter(!exp == "SYN22-5" | !source == "Culture") %>% 
  group_by(exp, exp_no, phyto, plot_datetime) %>% 
   summarize(across(
    .cols = fsc:yel,
    .fns = list(mean = mean, sd = sd),
    na.rm = TRUE,
    .names = "{fn}_{col}"
  ))  %>% 
  ungroup() %>% 
  group_by(exp) %>% 
  mutate_at(vars(5,7, 9,11), ~ ./(first(.))) %>% 
  ungroup() %>% 
  arrange(factor(phyto, levels = c("italic('T. pseudonana')", "italic('Synechococcus ') (WH8102)", "italic('O. lucimarinus')")))
  
```


- 

```{r forward scatter plot, message=FALSE, warning=FALSE, wrapper = TRUE}
fsc <-  ggplot() +
  geom_rect(
    data = shade,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
   geom_rect(
    data = shade.pre,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_errorbar(
    data = fcm_data,
    # data = fcm_data %>% filter(!exp == "SYN22-5" | !source == "Culture"),
    aes(
      x = plot_datetime,
      y = mean_fsc,
      ymin = mean_fsc - sd_fsc,
      ymax = mean_fsc + sd_fsc,
      color = factor(phyto, levels = unique(fcm_data$phyto)),
      group = interaction(phyto, exp_no)
    ),
    width = 2000,
    alpha = 0.7
  ) +
  geom_line(
    data = fcm_data,
    # data = fcm_data %>% filter(!exp == "SYN22-5" | !source == "Culture"),
    aes(
      x = plot_datetime,
      y = mean_fsc,
      color = factor(phyto, levels = unique(fcm_data$phyto)),
      linetype = as.character(exp_no),
      group = interaction(phyto, exp_no)
    ),
    size = 1,
    alpha = 0.7
  ) +
  geom_point(
    data = fcm_data,
    # data = fcm_data %>% filter(!exp == "SYN22-5" | !source == "Culture"),
    aes(
      x = plot_datetime,
      y = mean_fsc,
      fill = factor(phyto, levels = unique(fcm_data$phyto)),
      group = interaction(phyto, exp_no)
    ),
    color = "black",
    size = 4,
    shape = 21
  ) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  scale_shape_manual(values = c(21, 22)) +
  scale_color_manual(values = phyto.colors) +
  scale_fill_manual(values = phyto.colors, labels = scales::parse_format()) +
  labs(
    x = "Hour",
    y = expression(bold(Forward ~ scattering)),
    shape = "",
    fill = "Experiment",
    linetype = expression(bold(Experiment))
  ) +
  guides(color = "none", fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(21) +
  custom.theme 


```

- 

```{r side scatter plot, message=FALSE, warning=FALSE, wrapper=TRUE}
ssc <-  ggplot() +
  geom_rect(
    data = shade,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
   geom_rect(
    data = shade.pre,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_errorbar(
  data = fcm_data,
    aes(
      x = plot_datetime,
      y = mean_ssc,
      ymin = mean_ssc - sd_ssc,
      ymax = mean_ssc + sd_ssc,
      color = factor(phyto, levels = unique(fcm_data$phyto)),
      group = interaction(phyto, exp_no)
    ),
    width = 2000,
    alpha = 0.7
  ) +
  geom_line(
    data = fcm_data,
    aes(
      x = plot_datetime,
      y = mean_ssc,
      color = factor(phyto, levels = unique(fcm_data$phyto)),
      linetype = as.character(exp_no),
      group = interaction(phyto, exp_no)
    ),
    size = 1,
    alpha = 0.7
  ) +
  geom_point(
    data = fcm_data,
    aes(
      x = plot_datetime,
      y = mean_ssc,
      fill = factor(phyto, levels = unique(fcm_data$phyto)),
      group = interaction(phyto, exp_no)
    ),
    color = "black",
    size = 4,
    shape = 21
  ) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  scale_shape_manual(values = c(21, 22)) +
  scale_color_manual(values = phyto.colors) +
  scale_fill_manual(values = phyto.colors, labels = scales::parse_format()) +
  labs(
    x = "Hour",
    y = expression(bold(Side ~ scattering)),
    shape = "",
    fill = "",
    linetype = expression(bold(Experiment))
  ) +
  guides(color = "none", fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(21) +
  custom.theme +
   theme(
  strip.background = element_blank(),
  strip.text.x = element_blank(),
  axis.text.y.right = element_blank(),
        axis.ticks.y.right = element_blank(),
        axis.line.y.right = element_blank()
) 

```

- 

```{r red fluorescence plot, message=FALSE, warning=FALSE, wrapper = TRUE}
red <-  ggplot() +
  geom_rect(
    data = shade,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
   geom_rect(
    data = shade.pre,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_errorbar(
     data = fcm_data %>% filter(!exp %in% c("SYN22-4", "SYN22-5")),
    aes(
      x = plot_datetime,
      y = mean_red,
      ymin = mean_red - sd_red,
      ymax = mean_red + sd_red,
      color = factor(phyto, levels = unique(fcm_data$phyto)),
      group = interaction(phyto, exp_no)
    ),
    width = 2000,
    alpha = 0.7
  ) +
  geom_line(
    data = fcm_data %>% filter(!exp %in% c("SYN22-4", "SYN22-5")),
    aes(
      x = plot_datetime,
        y = mean_red,
        color = factor(phyto, levels = unique(fcm_data$phyto)),
        linetype = as.character(exp_no),
        group = interaction(phyto, exp_no)),
    size = 1,
    alpha = 0.7
  ) +
  geom_point(
     data = fcm_data %>% filter(!exp %in% c("SYN22-4", "SYN22-5")),
    aes(
      x = plot_datetime,
        y = mean_red,
        fill = factor(phyto, levels = unique(fcm_data$phyto)),
         group = interaction(phyto, exp_no)),
    color = "black",
    size = 4, 
    shape = 21
  ) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  scale_shape_manual(values = c(21, 22)) +
  scale_color_manual(values = phyto.colors) +
  scale_fill_manual(values = phyto.colors, labels = scales::parse_format()) +
  labs(x = "Hour",
       y = expression(bold(atop(Red~fluorescence, (695/50~nm)))),
       shape = "",
       fill = "",
       linetype = expression(bold(Experiment))) +
  guides(color = "none", fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(21) +
  custom.theme
```

-


```{r yellow fluorescence plot, message=FALSE, warning=FALSE, wrapper = TRUE}
yel <-  ggplot() +
  geom_rect(
    data = shade,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
   geom_rect(
    data = shade.pre,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_errorbar(
     # data = fcm_data %>% filter(!exp == "SYN22-5" | !source == "Culture") %>% filter(exp %in% c("SYN22-4", "SYN22-5")),
      # data = fcm_data %>% filter(!exp == "SYN22-5" | !source == "Culture"),
     data = fcm_data %>% filter(exp %in% c("SYN22-4", "SYN22-5")),
    aes(
      x = plot_datetime,
      y = mean_yel,
      ymin = mean_yel - sd_yel,
      ymax = mean_yel + sd_yel,
      color = factor(phyto, levels = unique(fcm_data$phyto)),
      group = interaction(phyto, exp_no)
    ),
    width = 2000,
    alpha = 0.7
  ) +
  geom_line(
    # data = fcm_data %>% filter(!exp == "SYN22-5" | !source == "Culture") %>% filter(exp %in% c("SYN22-4", "SYN22-5")),
    # data = fcm_data %>% filter(!exp == "SYN22-5" | !source == "Culture"),
     data = fcm_data[!is.na(fcm_data$mean_yel),] %>% filter(exp %in% c("SYN22-4", "SYN22-5")),
    aes(
      x = plot_datetime,
        y = mean_yel,
        color = factor(phyto, levels = unique(fcm_data$phyto)),
        linetype = as.character(exp_no),
        group = interaction(phyto, exp_no)),
    size = 1,
    alpha = 0.7
  ) +
  geom_point(
     # data = fcm_data %>% filter(!exp == "SYN22-5" | !source == "Culture") %>% filter(exp %in% c("SYN22-4", "SYN22-5")),
    # data = fcm_data %>% filter(!exp == "SYN22-5" | !source == "Culture"),
     data = fcm_data %>% filter(exp %in% c("SYN22-4", "SYN22-5")),
    aes(
      x = plot_datetime,
        y = mean_yel,
        fill = factor(phyto, levels = unique(fcm_data$phyto)),
         group = interaction(phyto, exp_no)),
    color = "black",
    size = 4, 
    shape = 21
  ) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  scale_shape_manual(values = c(21, 22)) +
  scale_color_manual(values = phyto.colors) +
  scale_fill_manual(values = phyto.colors, labels = scales::parse_format()) +
  labs(x = "Hour",
       y = expression(bold(atop(Yellow~fluorescence, (583/26~nm)))),
       shape = "",
       fill = "",
       linetype = expression(bold(Experiment))) +
  guides(color = "none", fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(21) +
  custom.theme 

```

-

```{r 2-fcm plot, fig.width=12, fig.asp=2, warning=FALSE, message=FALSE, wrapper = TRUE}
(fsc + guides(fill = "none") + theme(axis.title.x = element_blank()) + labs(tag = "a")) / (ssc + guides(fill = "none") + theme(axis.title.x = element_blank()) + labs(tag = "b")) / (red + theme(axis.title.x = element_blank()) + labs(tag = "c")) / (yel + labs(tag = "d"))  + plot_layout(guides = "collect", heights = c(1, 1, 1, 1))  &
  theme(legend.position = "bottom",
        legend.box="vertical",
        plot.tag = element_text(face = "bold"))
```


########################### 

# FRR

########################### 

```{r subset frr data, wrapper=TRUE}
frr_data <- sf %>%
  select(exp, exp_no, phyto, tp, plot_datetime, mean_Fo:sd_Fv_Fo) %>% 
  drop_na(mean_Fv_Fm) %>% 
  arrange(factor(phyto, levels = c("italic('T. pseudonana')", "italic('Synechococcus ') (WH8102)", "italic('O. lucimarinus')")))
```


```{r 3-frr plot, fig.width=12, fig.asp=0.8, warning=FALSE, wrapper=TRUE}
fvfm <- ggplot() +
  geom_rect(
    data = shade,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
   geom_rect(
    data = shade.pre,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_errorbar(
    data = frr_data,
    aes(
      x = plot_datetime,
      y = mean_Fv_Fm,
      ymin = mean_Fv_Fm - sd_Fv_Fm,
      ymax = mean_Fv_Fm + sd_Fv_Fm,
      color = factor(phyto, levels = unique(frr_data$phyto)),
      group = interaction(phyto, exp_no)
    ),
    width = 2000,
    alpha = 0.7
  ) +
  geom_line(
    data = frr_data,
    aes(
      x = plot_datetime,
      y = mean_Fv_Fm,
      color = factor(phyto, levels = unique(frr_data$phyto)),
      linetype = as.character(exp_no),
      group = interaction(phyto, exp_no)
    ),
    alpha = 0.7,
    size = 1
  ) +
  geom_point(
    data = frr_data,
    aes(
      x = plot_datetime,
      y = mean_Fv_Fm,
      fill = factor(phyto, levels = unique(frr_data$phyto)),
      group = interaction(phyto, exp_no)
    ),
    color = "black",
    shape = 21,
    size = 4
  ) +
  labs(
    x = "Hour",
    y = expression(bold(F[v] / F[m])),
    fill = "",
    linetype = "Experiment"
  ) +
  guides(color = "none", fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(18) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  scale_shape_manual(values = c(21, 22)) +
  scale_color_manual(values = phyto.colors) +
  scale_fill_manual(values = phyto.colors, labels = scales::parse_format()) +
  theme_linedraw(21) +
  custom.theme 

fvfm &
    theme(legend.position = "bottom",
           legend.box="vertical",
        plot.tag = element_text(face = "bold"))


```



########################### 

# CHL & POC

########################### 


```{r subset optics bottle data, wrapper=TRUE}
optics_data <- bf %>%
  filter(source == "Optics", wl %in% c(470, 532, 660)) %>%
  select(exp, exp_no, phyto, bottle, tp, plot_datetime,  wl, cells, chl_line_height,  poc_optics, pon_optics, cp, ap, bp,  bbp, bb_b) %>% 
  mutate_at(vars(cells), ~ . * 1E6) %>%  # convert cell abundance from cells/ml to m^-3
  mutate_at(vars(poc_optics, pon_optics), ~ . / 1E3) %>% # convert from mg/m3 to g/m3
  mutate_at(vars(wl), as.character) %>%
  distinct() %>% 
  mutate(chl_cell = (chl_line_height/cells) * 10^12, # mg chl/cell to fg chl per cell
         poc_cell = (poc_optics/cells) * 10^12, #g/cell convert to pg c per cell
         pon_cell = (pon_optics/cells) * 10^12, #g/cell convert to pg n per cell
         c_chl = ((poc_optics * 1E3)/chl_line_height), #mg to mg
         a_star = ap / (chl_line_height / 1E3), # m2 per g chl
         sigma_a = (ap / cells)  * 10^12, #m2 per cell * 10^12
         a_poc = ap / poc_optics, #m2 per g C
         c_star = cp /  (chl_line_height / 1E3),
         sigma_c = (cp / cells) * 10^12,
         c_poc = cp / poc_optics,
         bb_star = bbp /  (chl_line_height / 1E3),
         sigma_bb = (bbp / cells) * 10^12,
         bb_poc = bbp / poc_optics,
         g = bbp / (ap + bbp)
         )
```

-

```{r summarize optics bottle data, message=FALSE, warning=FALSE, wrapper=TRUE}
optics_summary <- optics_data %>% 
  group_by(exp, exp_no, phyto, tp, plot_datetime,  wl) %>% 
   summarize(across(
    .cols = cells:g,
    .fns = list(mean = mean, sd = sd),
    na.rm = TRUE,
    .names = "{fn}_{col}"
  ))  %>% 
     ungroup() %>% 
  arrange(factor(phyto, levels = unique(optics_data$phyto)))
```

- 

```{r pivot carbon and chl data, message=FALSE, warning=FALSE, wrapper=TRUE}
cell_cont_data <-  bf %>%
  filter(source == "Optics") %>%
  select(exp, exp_no, phyto, tp, plot_datetime,  poc_optics, sd_poc_optics, pon_optics, sd_pon_optics, mean_cn, sd_cn) %>% 
  distinct() %>% 
  mutate_at(vars(poc_optics, sd_poc_optics, pon_optics, sd_pon_optics), ~ . / 1E3) %>% # convert to g
  left_join(., optics_summary %>% select(exp:plot_datetime,mean_chl_line_height, sd_chl_line_height, mean_chl_cell, sd_chl_cell,mean_c_chl, sd_c_chl, mean_poc_cell, sd_poc_cell, mean_pon_cell, sd_pon_cell)) %>% 
  select(exp:sd_poc_optics, mean_poc_cell, sd_poc_cell, mean_pon_cell, sd_pon_cell, mean_cn:sd_c_chl) %>% 
  pivot_longer(cols = c(6:19), names_to = "param", values_to = "value") %>% 
mutate(sd = ifelse(str_detect(param, "sd"), value, NA),
         value = ifelse(str_detect(param, "sd"), NA, value),
         param = gsub("mean_", "", param),
         param = gsub("sd_", "", param)) %>% 
  group_by(exp, exp_no, phyto, tp, plot_datetime, param ) %>% 
  fill(value, sd, .direction = "updown") %>% 
  distinct() %>% 
  ungroup() %>% 
  mutate(param_label = case_when(param == "poc_optics" ~ "POC ~ (g ~ C ~ m ^ -3)",
                                 param == "pon_optics" ~ "PON ~ (g ~ N ~ m ^ -3)",
                                param == "poc_cell" ~ "POC ~ (pg ~ C ~ cell ^ -1)",
                                param == "pon_cell" ~ "PON ~ (pg ~ N ~ cell ^ -1)",
                                param == "cn" ~ "C:N",
                                param == "chl_line_height" ~ "Chl-italic(a) ~ (mg ~ m ^ -3)",
                                param == "chl_cell" ~ "Chl-italic(a) ~ (pg ~ cell ^ -1)",
                                param == "c_chl" ~ "C:Chl-italic(a)")) %>% 
  filter(!param %in% c("poc_optics", "chl_line_height"))
```

-

```{r 4-chl and poc plot, fig.asp=0.86, fig.width=20, warning=FALSE, message=FALSE, wrapper = TRUE}
ggplot() +
  geom_rect(
    data = shade,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
   geom_rect(
    data = shade.pre,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_errorbar(
    data = cell_cont_data[!is.na(cell_cont_data$value),],
    aes(
      x = plot_datetime,
      y = value,
      ymin = value - sd,
      ymax = value + sd,
      color = phyto,
      group = interaction(phyto, exp_no)
    ),
    width = 2000,
    alpha = 0.7
  ) +
  geom_line(
    data = cell_cont_data[!is.na(cell_cont_data$value),],
    aes(
      x = plot_datetime,
      y = value,
      color = phyto,
      linetype = as.character(exp_no),
      group = interaction(phyto, exp_no)
    ),
    alpha = 0.7,
    size = 1
  ) +
  geom_point(
    data = cell_cont_data[!is.na(cell_cont_data$value),],
    aes(
      x = plot_datetime,
      y = value,
      fill = factor(phyto, levels = unique(cell_cont_data$phyto)),
      group = interaction(phyto, exp_no)
    ),
    shape = 21,
    color = "black",
    size = 4
  ) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  scale_y_continuous(breaks = scales::breaks_pretty()) +
  scale_color_manual(values = phyto.colors) +
  scale_fill_manual(values = phyto.colors, labels = scales::parse_format()) +
  labs(x =  "Hour",
       y = "",
       fill = "",
       linetype = "Experiment") +
  ggh4x::facet_grid2(factor(param_label, levels = unique(cell_cont_data$param_label)) ~ factor(phyto, levels = unique(cell_cont_data$phyto)),
              scales = "free_y",
              independent = "y",
              labeller = label_parsed,
              switch = "y") +
  guides(color = "none", fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(21) +
  custom.theme +
  theme(strip.placement = "outside",
        strip.background.y = element_blank())
```

-

#############

# PIGMENTS

############## 

-

```{r single spectra, fig.asp=0.5, fig.width=18}
spec_decomp <- gaus %>%
  filter(exp_no == 2, tp == 1) %>%
  distinct() %>%
  ggplot() +
  geom_line(
    aes(
      x = wl,
      y = ap,
      color = spectra_label,
      group = interaction(phyto, spectra,  exp_no)
    ),
    size = 1,
    alpha = 0.7
  ) +
  labs(x = expression(bold(Wavelength ~ nm ^ -1)),
        y = expression(bold(italic(a[p]) ~ (
         m ^ -1))),
       color = "") +
  facet_wrap( ~ factor(phyto, levels = unique(gaus$phyto)),
              # scales = "free_y",
              labeller = label_parsed) +
  scale_color_manual(values = gaus.colors) +
  theme_linedraw(21) +
  custom.theme 
  
```

-

```{r tp pigment ratios, message=FALSE, warning=FALSE}
ratios.data <- pigs %>% 
  filter(spectra %in% c("ppc_chla", "psc_chla", "ppc_chla", "pub_peb", "pe_chla", "chlb_chla")) %>% 
  mutate(peak = ifelse(peak == Inf, NA, peak))

tp_pigs <- ggplot() +
  geom_rect(
    data = shade,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
   geom_rect(
    data = shade.pre,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
   geom_rect(
    data = shade.pre,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_line(
    data = ratios.data %>% filter(phyto == "italic('T. pseudonana')" & spectra %in% c("ppc_chla", "psc_chla")),
    aes(
      x = plot_datetime,
      y = peak,
      linetype = as.character(exp_no),
      group = interaction(phyto, exp_no, spectra)
    ),
   color = "black",
    size = 1,
    alpha = 0.7
  ) +
  geom_point(
    data = ratios.data %>% filter(phyto == "italic('T. pseudonana')" & spectra %in% c("ppc_chla", "psc_chla")),
    aes(x = plot_datetime,
        y = peak,
      group = interaction(phyto, exp_no, spectra)
    ),
    shape = 21,
    size = 4,
    fill = "black",
    color = "black"
  ) +
  labs(x =  expression(bold(Hour)),
       y = expression(bold(Ratio)),
       shape = "",
       fill = "",
       linetype = "Experiment",
       title = expression(italic(T.~pseudonana))) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  facet_wrap(~factor(spectra_label, levels = unique(ratios.data$spectra_label)),
             scales = "free_y",
              labeller = label_parsed) + 
  scale_shape_manual(values = c(21, 22)) +
  guides(color = "none", fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(21) +
  custom.theme
```

-

```{r syn pigment ratios, message=FALSE, warning=FALSE}
syn_pigs <- ggplot() +
  geom_rect(
    data = shade,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
   geom_rect(
    data = shade.pre,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_line(
    data = ratios.data %>% filter(phyto == "italic('Synechococcus ') (WH8102)" & spectra %in% c("pe_chla", "pub_peb")),
    aes(
      x = plot_datetime,
      y = peak,
      linetype = as.character(exp_no),
      group = interaction(phyto, exp_no, spectra)
    ),
    size = 1,
    alpha = 0.7,
    color = "black"
  ) +
  geom_point(
    data = ratios.data %>% filter(phyto == "italic('Synechococcus ') (WH8102)" & spectra %in% c("pe_chla", "pub_peb")),
    aes(x = plot_datetime,
        y = peak,
      group = interaction(phyto, exp_no, spectra)
    ),
    shape = 21,
    size = 4,
    color = "black",
    fill = "black"
  ) +
  labs(x =  expression(bold(Hour)),
       y = expression(bold(Ratio)),
       shape = "",
       fill = "",
       linetype = "Experiment",
       title = expression(italic(Synechococcus~(WH8102)))) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  scale_shape_manual(values = c(21, 22)) +
 facet_wrap(~factor(spectra_label, levels = unique(ratios.data$spectra_label)),
             scales = "free_y",
              labeller = label_parsed) + 
  guides(color = "none", fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(21) +
  custom.theme
```

-

```{r ol pigment ratios, message=FALSE, warning=FALSE}
ol_pigs <- ggplot() +
  geom_rect(
    data = shade,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
   geom_rect(
    data = shade.pre,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_line(
    data = ratios.data %>% filter(phyto == "italic('O. lucimarinus')" & spectra %in% c("ppc_chla", "chlb_chla")),
    aes(
      x = plot_datetime,
      y = peak,
      linetype = as.character(exp_no),
      group = interaction(phyto, exp_no, spectra)
    ),
    color = "black",
    size = 1,
    alpha = 0.7
  ) +
  geom_point(
    data = ratios.data %>% filter(phyto == "italic('O. lucimarinus')" & spectra %in% c("ppc_chla", "chlb_chla")),
    aes(x = plot_datetime,
        y = peak,
      group = interaction(phyto, exp_no, spectra)
    ),
    shape = 21,
    size = 4,
    color = "black",
    fill = "black"
  ) +
  labs(x =  expression(bold(Hour)),
       y = expression(bold(Ratio)),
       shape = "",
       fill = "",
       linetype = "Experiment",
       title = expression(italic(O.~lucimarinus))) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  scale_shape_manual(values = c(21, 22)) +
  facet_wrap(~factor(spectra_label, levels = unique(ratios.data$spectra_label)),
             scales = "free_y",
              labeller = label_parsed) + 
  guides(color = "none", fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(21) +
  custom.theme
```

-

```{r 5-pig ratios plot, fig.asp=1.4, fig.width=18, warning=FALSE, message=FALSE, wrapper = TRUE}
(tp_pigs + guides(linetype = "none") + labs(tag = "a") + theme(axis.title.x = element_blank())) / (syn_pigs + labs(tag = "b") + theme(axis.title.x = element_blank())) / (ol_pigs  + labs(tag = "c")) + plot_layout(guides = "collect", heights = c(1, 1, 1)) &
    theme(legend.position = "bottom",
           legend.box="vertical",
        plot.tag = element_text(face = "bold"))
```

-


########################### 

# BULK OPTICS

########################### 

- 

```{r ap, message=FALSE, warning=FALSE, wrapper=TRUE}
a <- ggplot() +
  geom_rect(
    data = shade,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_rect(
    data = shade.pre,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_errorbar(
    data = optics_summary,
    aes(
      x = plot_datetime,
      y = mean_ap,
      ymin = mean_ap - sd_ap,
      ymax = mean_ap + sd_ap,
      color = wl,
      group = interaction(phyto, exp_no, wl)
    ),
    width = 2000,
    alpha = 0.7
  ) +
  geom_line(
    data = optics_summary,
    aes(
      x = plot_datetime,
      y = mean_ap,
      color = wl,
      linetype = as.character(exp_no),
      group = interaction(phyto, exp_no, wl)
    ),
    alpha = 0.7,
    size = 1
  ) +
  geom_point(
    data = optics_summary,
    aes(
      x = plot_datetime,
      y = mean_ap,
      fill = wl,
      group = interaction(phyto, exp_no, wl)
    ),
    shape = 21,
    color = "black",
    size = 4
  ) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  scale_y_continuous(breaks = scales::breaks_pretty()) +
  scale_shape_manual(values = c(21, 22)) +
  scale_color_manual(values = bb3.colors) +
  scale_fill_manual(values = bb3.colors, labels = scales::parse_format()) +
  labs(x =  "Hour",
       y = expression(bold(italic(a[p])  ~ (
         m ^ -1))),
       fill = expression(bold(Wavelength ~ (nm))),
       linetype = expression(bold(Experiment))) +
  facet_wrap( ~ factor(phyto, levels = unique(optics_summary$phyto)),
              # scales = "free_y",
              labeller = label_parsed) +
  guides(color = "none", fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(21) +
  custom.theme
```

-

```{r cp, message=FALSE, warning=FALSE, wrapper=TRUE}
c <- ggplot() +
  geom_rect(
    data = shade,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
   geom_rect(
    data = shade.pre,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_errorbar(
    data = optics_summary,
    aes(
      x = plot_datetime,
      y = mean_cp,
      ymin = mean_cp - sd_cp,
      ymax = mean_cp + sd_cp,
      color = wl,
      group = interaction(phyto, exp_no, wl)
    ),
    width = 2000,
    alpha = 0.7
  ) +
  geom_line(
    data = optics_summary,
    aes(
      x = plot_datetime,
      y = mean_cp,
      color = wl,
      linetype = as.character(exp_no),
      group = interaction(phyto, exp_no, wl)
    ),
    alpha = 0.7,
    size = 1
  ) +
  geom_point(
    data = optics_summary,
    aes(
      x = plot_datetime,
      y = mean_cp,
      fill = wl,
      group = interaction(phyto, exp_no, wl)
    ),
    shape = 21,
    color = "black",
    size = 4
  ) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  scale_y_continuous(breaks = scales::breaks_pretty()) +
  scale_shape_manual(values = c(21, 22)) +
  scale_color_manual(values = bb3.colors) +
  scale_fill_manual(values = bb3.colors, labels = scales::parse_format()) +
  labs(x =  "Hour",
       y = expression(bold(italic(c[p])  ~ (
         m ^ -1))),
       fill = expression(bold(Wavelength ~ (nm))),
       linetype = expression(bold(Experiment))) +
  facet_wrap( ~ factor(phyto, levels = unique(optics_summary$phyto)),
              # scales = "free_y",
              labeller = label_parsed) +
  guides(color = "none", fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(21) +
  custom.theme +
   theme(
  strip.background = element_blank(),
  strip.text.x = element_blank(),
  axis.text.y.right = element_blank(),
        axis.ticks.y.right = element_blank(),
        axis.line.y.right = element_blank() )
```

- 

```{r bbp, message=FALSE, warning=FALSE, wrapper=TRUE}
bb <- ggplot() +
  geom_rect(
    data = shade,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
   geom_rect(
    data = shade.pre,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_errorbar(
    data = optics_summary,
    aes(
      x = plot_datetime,
      y = mean_bbp,
      ymin = mean_bbp - sd_bbp,
      ymax = mean_bbp + sd_bbp,
      color = wl,
      group = interaction(phyto, exp_no, wl)
    ),
    width = 2000,
    alpha = 0.7
  ) +
  geom_line(
    data = optics_summary,
    aes(
      x = plot_datetime,
      y = mean_bbp,
      color = wl,
      linetype = as.character(exp_no),
      group = interaction(phyto, exp_no, wl)
    ),
    alpha = 0.7,
    size = 1
  ) +
  geom_point(
    data = optics_summary,
    aes(
      x = plot_datetime,
      y = mean_bbp,
      fill = wl,
      group = interaction(phyto, exp_no, wl)
    ),
    shape = 21,
    color = "black",
    size = 4
  ) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  scale_y_continuous(breaks = scales::breaks_pretty()) +
  scale_shape_manual(values = c(21, 22)) +
  scale_color_manual(values = bb3.colors) +
  scale_fill_manual(values = bb3.colors, labels = scales::parse_format()) +
  labs(x =  "Hour",
       y = expression(bold(italic(b[bp])  ~ (
         m ^ -1))),
       fill = expression(bold(Wavelength ~ (nm))),
       linetype = expression(bold(Experiment))) +
  facet_wrap( ~ factor(phyto, levels = unique(optics_summary$phyto)),
              # scales = "free_y",
              labeller = label_parsed) +
  guides(color = "none", fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(21) +
  custom.theme +
   theme(
  strip.background = element_blank(),
  strip.text.x = element_blank(),
  axis.text.y.right = element_blank(),
        axis.ticks.y.right = element_blank(),
        axis.line.y.right = element_blank() )
```


```{r bb/b, message=FALSE, warning=FALSE, wrapper=TRUE}
bbp.bb <-  ggplot() +
  geom_rect(
    data = shade,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
   geom_rect(
    data = shade.pre,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_errorbar(
    data = optics_summary,
    aes(
      x = plot_datetime,
      y = mean_bb_b,
      ymin = mean_bb_b - sd_bb_b,
      ymax = mean_bb_b + sd_bb_b,
      color = wl,
      group = interaction(phyto, exp_no, wl)
    ),
    width = 2000,
    alpha = 0.7
  ) +
  geom_line(
    data = optics_summary,
    aes(
      x = plot_datetime,
      y = mean_bb_b,
      color = wl,
      linetype = as.character(exp_no),
      group = interaction(phyto, exp_no, wl)
    ),
    alpha = 0.7,
    size = 1
  ) +
  geom_point(
    data = optics_summary,
    aes(
      x = plot_datetime,
      y = mean_bb_b,
      fill = wl,
      group = interaction(phyto, exp_no, wl)
    ),
    shape = 21,
    color = "black",
    size = 4
  ) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  scale_shape_manual(values = c(21, 22)) +
  scale_color_manual(values = bb3.colors) +
  scale_fill_manual(values = bb3.colors, labels = scales::parse_format()) +
  labs(x =  "Hour",
       y = expression(bold(italic(b[bp]) ~ "/" ~ italic(b[b]))),
       fill = expression(bold(Wavelength ~ (nm))),
       linetype = expression(bold(Experiment))) +
  facet_wrap( ~ factor(phyto, levels = unique(optics_summary$phyto)),
              # scales = "free_y",
              labeller = label_parsed) +
  guides(color = "none", fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(21) +
  custom.theme +
   theme(
  strip.background = element_blank(),
  strip.text.x = element_blank(),
  axis.text.y.right = element_blank(),
        axis.ticks.y.right = element_blank(),
        axis.line.y.right = element_blank() )
```

-

```{r 6-bulk optics plot, fig.asp=1.4, fig.width=18, warning=FALSE, message=FALSE, wrapper = TRUE}
(a + guides(fill = "none") + labs(tag = "a") + theme(axis.title.x = element_blank())) / (c + guides(fill = "none") + labs(tag = "b") + theme(axis.title.x = element_blank())) / (bb + guides(fill = "none")  + labs(tag = "c") + theme(axis.title.x = element_blank())) / (bbp.bb + labs(tag = "d")) + plot_layout(guides = "collect", heights = c(1, 1, 1, 1)) &
    theme(legend.position = "bottom",
        plot.tag = element_text(face = "bold"))
```

########################### 

# CORRELATIONS

########################### 



```{r 7-correlations plot, fig.asp=1.2, fig.width=20, warning=FALSE, message=FALSE, wrapper = TRUE}

corr <- read_csv("Correlations.csv") %>% 
  mutate(var3 = case_when(var1 == "ap" ~ "italic(a[p])",
                          var1 == "cp" ~ "italic(c[p])",
                          var1 == "bbp" ~ "italic(b[bp])",
                          var1 == "bb_b" ~  "'*' ~ italic(b[bp]) ~ '/' ~ italic(b[b])")) %>% 
  mutate(var4 = case_when(var2 == "ap" ~ "italic(a[p])",
                          var2 == "cp" ~ "italic(c[p])",
                          var2 == "bbp" ~ "italic(b[bp])",
                          var2 == "bb_b" ~  "'*' ~ italic(b[bp]) ~ '/' ~ italic(b[b])", 
                          var2 == "cells" ~ "Cells",
                          var2 == "fsc" ~ "'*'~FSC",
                          var2 == "ssc" ~ "'*'~SSC",
                          var2 == "poc_optics" ~ "POC",
                          var2 == "poc_cell" ~ "'*'~POC~per~cell",
                          var2 == "cn" ~ "'*'~C:N",
                          var2 == "c_chl" ~ "'*'~C:Chl",
                          var2 == "chl_line_height" ~ "paste('Chl-', italic('a'))",
                          var2 == "chl_cell" ~ "paste('*Chl-', italic('a'), ' per cell')",
                          var2 ==  "ppc_chla" ~ "paste('*PPC:Chl-', italic('a'))",
                          var2 ==  "psc_chla" ~ "paste('*PSC:Chl-', italic('a'))",
                          var2 ==  "pe_chla" ~ "paste('*PE:Chl-', italic('a'))",
                          var2 ==  "chlb_chla" ~ "paste('*Chl-', italic('b'),':Chl-', italic('a'))",
                          var2 ==  "pub_peb" ~ "'*'~PUB:PEB",
                          var2 == "Fv_Fm" ~ "paste('*F'[v], '/', 'F'[m])",
                          var2 == "red" ~ "'*'~Red~fluor."
                          ) ) %>% 
  mutate(phyto = case_when(phyto == "t_pseudonana" ~ "italic('T. pseudonana')",
                           phyto == "synechococcus" ~ "italic('Synechococcus ') (WH8102)",
                           phyto == "o_lucimarinus" ~ "italic('O. lucimarinus')") )  %>% 
  mutate(wl = case_when(wl == "470" ~ "470~nm",
                        wl == "532" ~ "532~nm",
                        wl == "660" ~ "660~nm",
                        )) %>% 
  mutate(cor = ifelse(p >= 0.05, NA, cor))
                        

cor_levels = c("italic(a[p])", "italic(c[p])", "italic(b[bp])", "'*' ~ italic(b[bp]) ~ '/' ~ italic(b[b])", "Cells", "'*'~FSC", "'*'~SSC","POC","'*'~POC~per~cell","'*'~C:N",  "'*'~C:Chl", "paste('Chl-', italic('a'))", "paste('*Chl-', italic('a'), ' per cell')",  "paste('*PPC:Chl-', italic('a'))",  "paste('*PSC:Chl-', italic('a'))", "paste('*PE:Chl-', italic('a'))","paste('*Chl-', italic('b'),':Chl-', italic('a'))",  "'*'~PUB:PEB", "paste('*F'[v], '/', 'F'[m])", "'*'~Red~fluor.")

cor_levels2 = c("italic('T. pseudonana')",  "italic('Synechococcus ') (WH8102)", "italic('O. lucimarinus')") 


ggplot(data = corr, aes(factor(wl, levels = unique(corr$wl)), factor(var4, levels = rev(cor_levels)), fill = cor)) +
  geom_tile(color = "white") + 
  geom_text(aes(label = cor), color = "black", size = 5, fontface = "bold") +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="Spearman's rho") +
  scale_x_discrete("", labels = scales::parse_format()) +
    scale_y_discrete("", labels = scales::parse_format()) +
  theme_linedraw(21) + 
  ggh4x::facet_grid2(factor(var3, levels = c(cor_levels)) ~ factor(phyto, levels = cor_levels2),
              scales = "free_y",
               independent = "y",
              labeller = label_parsed) +
  custom.theme +
  theme(legend.position = "bottom", legend.key.width = unit(2.5, "cm"))
  
```



########################### 

# MASS-SPECFIC

########################### 

```{r pivot optical data, warning=FALSE, message=FALSE, wrapper = TRUE}
mass_sp <- optics_summary %>% 
  select(exp:wl, mean_a_star:sd_bb_poc) %>% 
  pivot_longer(cols = c(7:24), names_to = "param", values_to = "value") %>% 
  mutate(sd = ifelse(str_detect(param, "sd"), value, NA),
         value = ifelse(str_detect(param, "sd"), NA, value),
         param = gsub("mean_", "", param),
         param = gsub("sd_", "", param)) %>% 
  group_by(exp, exp_no, phyto, tp, plot_datetime, wl, param ) %>% 
  fill(value, sd, .direction = "updown") %>% 
  distinct() %>% 
  ungroup() %>% 
  mutate(prop = case_when(param %in% c("a_star", "sigma_a", "a_poc") ~ "a",
                          param %in% c("c_star", "sigma_c", "c_poc") ~ "c",
                          param %in% c("bb_star", "sigma_bb", "bb_poc") ~ "bb"),
         norm = ifelse(str_detect(param, "star"), "star",  NA),
         norm = ifelse(str_detect(param, "sigma"), "sigma", norm),
         norm = ifelse(str_detect(param, "poc"), "poc", norm),
         .before = param) %>% 
  select(-param) %>% 
  mutate(prop_label = case_when(prop == "a" ~ "italic(a[p])",
                                prop == "c" ~ "italic(c[p])",
                                prop == "bb" ~ "italic(b[bp])"),
         
         norm_label = case_when(norm == "star" ~ "m^2 ~ g ~ chl-italic(a)^-1",
                                norm == "sigma" ~ "(m^2 ~ cell^-1) ~'*'~10^12",
                                norm == "poc" ~ "m^2 ~ g ~ C^-1") )
  
```

-

```{r mass specific tp, warning=FALSE, message=FALSE, wrapper = TRUE}
mass_sp_tp <- ggplot() +
  geom_rect(
    data = shade,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
   geom_rect(
    data = shade.pre,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_errorbar(
    data = mass_sp[!is.na(mass_sp$value),] %>% filter(phyto == "italic('T. pseudonana')"),
    aes(
      x = plot_datetime,
      y = value,
      ymin = value - sd,
      ymax = value + sd,
      color = wl,
      group = interaction(phyto, exp_no, wl)
    ),
    width = 2000,
    alpha = 0.7
  ) +
  geom_line(
    data = mass_sp[!is.na(mass_sp$value),] %>% filter(phyto == "italic('T. pseudonana')"),
    aes(
      x = plot_datetime,
      y = value,
      color = wl,
      group = interaction(phyto, exp_no, wl)
    ),
    linetype = "dashed",
    alpha = 0.7,
    size = 1
  ) +
  geom_point(
    data = mass_sp[!is.na(mass_sp$value),] %>% filter(phyto == "italic('T. pseudonana')"),
    aes(
      x = plot_datetime,
      y = value,
      fill = wl,
      group = interaction(phyto, exp_no, wl)
    ),
    shape = 21,
    color = "black",
    size = 4
  ) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  # scale_y_continuous(labels = scientific_10, breaks = scales::breaks_pretty()) +
  scale_y_continuous(breaks = scales::breaks_pretty()) +
  scale_shape_manual(values = c(21, 22)) +
  scale_color_manual(values = bb3.colors) +
  scale_fill_manual(values = bb3.colors, labels = scales::parse_format()) +
  labs(x =  "Hour",
       y = "",
       fill = expression(bold(Wavelength ~ (nm))),
       linetype = "",
       title = expression(italic(T.~pseudonana))) +
  ggh4x::facet_grid2(factor(norm_label, levels = unique(mass_sp$norm_label)) ~ factor(prop_label, levels = unique(mass_sp$prop_label)),
              scales = "free_y",
               independent = "y",
              labeller = label_parsed) +
  guides(color = "none", linetype = "none", fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(21) +
  custom.theme 
```


-

```{r mass sp syn, warning=FALSE, message=FALSE, wrapper = TRUE}
mass_sp_syn <- ggplot() +
  geom_rect(
    data = shade,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
   geom_rect(
    data = shade.pre,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_errorbar(
    data = mass_sp[!is.na(mass_sp$value),] %>% filter(phyto == "italic('Synechococcus ') (WH8102)"),
    aes(
      x = plot_datetime,
      y = value,
      ymin = value - sd,
      ymax = value + sd,
      color = wl,
      group = interaction(phyto, exp_no, wl)
    ),
    width = 2000,
    alpha = 0.7
  ) +
  geom_line(
    data = mass_sp[!is.na(mass_sp$value),] %>% filter(phyto == "italic('Synechococcus ') (WH8102)"),
    aes(
      x = plot_datetime,
      y = value,
      color = wl,
      linetype = as.character(exp_no),
      group = interaction(phyto, exp_no, wl)
    ),
    alpha = 0.7,
    size = 1
  ) +
  geom_point(
    data = mass_sp[!is.na(mass_sp$value),] %>% filter(phyto == "italic('Synechococcus ') (WH8102)"),
    aes(
      x = plot_datetime,
      y = value,
      fill = wl,
      group = interaction(phyto, exp_no, wl)
    ),
    shape = 21,
    color = "black",
    size = 4
  ) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  # scale_y_continuous(labels = scientific_10, breaks = scales::breaks_pretty()) +
  scale_y_continuous(breaks = scales::breaks_pretty()) +
  scale_shape_manual(values = c(21, 22)) +
  scale_color_manual(values = bb3.colors) +
  scale_fill_manual(values = bb3.colors, labels = scales::parse_format()) +
  labs(x =  "Hour",
       y = "",
       fill = expression(bold(Wavelength ~ (nm))),
       linetype = expression(bold(Experiment)),
       title = expression(italic(Synechococcus~(WH8102)))) +
  ggh4x::facet_grid2(factor(norm_label, levels = unique(mass_sp$norm_label)) ~ factor(prop_label, levels = unique(mass_sp$prop_label)),
              scales = "free_y",
               independent = "y",
              labeller = label_parsed) +
  guides(color = "none", fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(21) +
  custom.theme 
```

-

```{r mass spec ol, warning=FALSE, message=FALSE, wrapper = TRUE}
mass_sp_ol <- ggplot() +
  geom_rect(
    data = shade,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
   geom_rect(
    data = shade.pre,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_errorbar(
    data = mass_sp[!is.na(mass_sp$value),] %>% filter(phyto == "italic('O. lucimarinus')"),
    aes(
      x = plot_datetime,
      y = value,
      ymin = value - sd,
      ymax = value + sd,
      color = wl,
      group = interaction(phyto, exp_no, wl)
    ),
    width = 2000,
    alpha = 0.7
  ) +
  geom_line(
    data = mass_sp[!is.na(mass_sp$value),] %>% filter(phyto == "italic('O. lucimarinus')"),
    aes(
      x = plot_datetime,
      y = value,
      color = wl,
      linetype = as.character(exp_no),
      group = interaction(phyto, exp_no, wl)
    ),
    alpha = 0.7,
    size = 1
  ) +
  geom_point(
    data = mass_sp[!is.na(mass_sp$value),] %>% filter(phyto == "italic('O. lucimarinus')"),
    aes(
      x = plot_datetime,
      y = value,
      fill = wl,
      group = interaction(phyto, exp_no, wl)
    ),
    shape = 21,
    color = "black",
    size = 4
  ) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  # scale_y_continuous(labels = scientific_10, breaks = scales::breaks_pretty()) +
  scale_y_continuous(breaks = scales::breaks_pretty()) +
  scale_shape_manual(values = c(21, 22)) +
  scale_color_manual(values = bb3.colors) +
  scale_fill_manual(values = bb3.colors, labels = scales::parse_format()) +
  labs(x =  "Hour",
       y = "",
       fill = expression(bold(Wavelength ~ (nm))),
       linetype = expression(bold(Experiment)),
       title = expression(italic(O.~lucimarinus))) +
  ggh4x::facet_grid2(factor(norm_label, levels = unique(mass_sp$norm_label)) ~ factor(prop_label, levels = unique(mass_sp$prop_label)),
              scales = "free_y",
               independent = "y",
              labeller = label_parsed) +
  guides(color = "none", fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(21) +
  custom.theme 
```

-

```{r 8-mass-specific optics plot, fig.asp=1.8, fig.width=18, warning=FALSE, message=FALSE, wrapper = TRUE}
(mass_sp_tp + guides(fill = "none") + labs(tag = "a") + theme(axis.title.x = element_blank())) / (mass_sp_syn + guides(fill = "none") + labs(tag = "b") + theme(axis.title.x = element_blank())) / (mass_sp_ol  + labs(tag = "c")) + plot_layout(guides = "collect", heights = c(1, 1, 1)) &
    theme(legend.position = "bottom",
        plot.tag = element_text(face = "bold"))
```

-

########################### 

# COEFFICIENT BOXPLOT

########################### 


```{r 9-boxplot, fig.asp=0.8, fig.width=22, warning=FALSE, message=FALSE, wrapper = TRUE}
ggplot(data = mass_sp) +
  geom_boxplot(
    aes(
      x = factor(phyto, levels = c(unique(mass_sp$phyto))),
      y = value,
      fill = wl,
      group = interaction(phyto, wl)
    ),
    alpha = 0.7,
    size = 1
  ) +
  scale_x_discrete("", labels = scales::parse_format()) +
  scale_fill_manual(values = bb3.colors) +
  scale_y_continuous(breaks = scales::breaks_pretty()) +
  geom_vline(xintercept = 1.5, linetype = "dashed") +
  geom_vline(xintercept = 2.5, linetype = "dashed") +
  labs(x =  "",
       y = "Biomass-specific coefficient",
       fill = expression(bold(Wavelength ~ (nm)))) +
  ggh4x::facet_grid2(factor(norm_label, levels = unique(mass_sp$norm_label)) ~ factor(prop_label, levels = unique(mass_sp$prop_label)),
              scales = "free_y",
               independent = "y",
              labeller = label_parsed) +
  theme_linedraw(21) +
  custom.theme +
  theme(axis.text.x = element_text(angle = 15,vjust = 0.7))

```


-

########################### 

# SUPPLEMENTARY MATERIAL

########################### 


```{r}
supp_data <- sf %>%
  filter(source == "Optics") %>%
  select(exp, exp_no, phyto, tp, time, plot_datetime,  wl, mean_ap, sd_ap, mean_cp, sd_cp) %>% 
  mutate(exp2 = paste(phyto, exp_no, sep = "~")) 
```


```{r ap plot, fig.asp=0.3, fig.width=30, wrapper=TRUE}
ap.plot <- supp_data %>%
  ggplot(aes(
    x = wl,
    y = mean_ap,
    color = time,
    group = interaction(exp, tp)
  )) +
  geom_errorbar(aes(ymin = mean_ap - sd_ap, ymax = mean_ap + sd_ap), alpha = 0.7) +
  geom_line(linewidth = 1) +
  labs(x = expression(bold(Wavelength ~ (nm ^ -1))),
       y = expression(bold(a[p] ~ (m ^ -1))),
       color = "Time") +
  scale_color_gradient2(
    trans = "hms",
    low = scales::muted("red"),
    mid = "white",
    high = scales::muted("blue"),
    midpoint = as.numeric(mean(supp_data$time)),
    na.value = "grey50",
    guide = guide_colorbar(
      frame.colour = "black",
      ticks.colour = "black"
    )
  ) +
  ggh4x::facet_grid2(~ factor(exp2, levels = unique(supp_data$exp2)),
              scales = "free_y",
               independent = "y",
              labeller = label_parsed) +
  theme_linedraw(21) +
  custom.theme +
  theme(legend.key.width = unit(5, "cm"))
```

```{r cp plot, fig.asp=0.3, fig.width=30, wrapper=TRUE}
cp.plot <- supp_data %>%
  ggplot(aes(
    x = wl,
    y = mean_cp,
    color = time,
    group = interaction(exp, tp)
  )) +
  geom_errorbar(aes(ymin = mean_cp - sd_cp, ymax = mean_cp + sd_cp), alpha = 0.7) +
  geom_line(linewidth = 1) +
  labs(x = expression(bold(Wavelength ~ (nm ^ -1))),
       y = expression(bold(c[p] ~ (m ^ -1))),
       color = "Time") +
  scale_color_gradient2(
    trans = "hms",
    low = scales::muted("red"),
    mid = "white",
    high = scales::muted("blue"),
    midpoint = as.numeric(mean(supp_data$time)),
    na.value = "grey50",
    guide = guide_colorbar(
      frame.colour = "black",
      ticks.colour = "black"
    )
  ) +
  ggh4x::facet_grid2(~ factor(exp2, levels = unique(supp_data$exp2)),
              scales = "free_y",
               independent = "y",
              labeller = label_parsed) +
  theme_linedraw(21) +
  custom.theme +
  theme(legend.key.width = unit(5, "cm"))
```
-

```{r supp fig, fig.asp=0.5, fig.width=30, message=FALSE, warning=FALSE, wrapper=TRUE}
(ap.plot + theme(axis.title.x = element_blank())) /  (cp.plot + guides(color = "none")) + plot_layout(guides = 'collect') + plot_annotation(tag_levels = 'a', title = "Mean and standard deviation of particulate absorption (a) and attenuation (b) spectra for replicate cultures over the timecourse of each experiment.")  &
  theme(legend.position = "bottom",
        plot.tag = element_text(face = "bold"),
        plot.title = element_text(size = 28)) 
```


```{r g, fig.asp=0.5, fig.width=16, message=FALSE, warning=FALSE, wrapper=TRUE}
g <-  ggplot() +
  geom_rect(
    data = shade,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
   geom_rect(
    data = shade.pre,
    aes(
      xmin = dusk,
      xmax = dawn,
      ymin = bottom,
      ymax = top
    ),
    fill = 'light grey',
    alpha = 0.4
  ) +
  geom_errorbar(
    data = optics_summary,
    aes(
      x = plot_datetime,
      y = mean_g,
      ymin = mean_g - sd_g,
      ymax = mean_g + sd_g,
      color = wl,
      group = interaction(phyto, exp_no, wl)
    ),
    width = 2000,
    alpha = 0.7
  ) +
  geom_line(
    data = optics_summary,
    aes(
      x = plot_datetime,
      y = mean_g,
      color = wl,
      linetype = as.character(exp_no),
      group = interaction(phyto, exp_no, wl)
    ),
    alpha = 0.7,
    size = 1
  ) +
  geom_point(
    data = optics_summary,
    aes(
      x = plot_datetime,
      y = mean_g,
      fill = wl,
      group = interaction(phyto, exp_no, wl)
    ),
    shape = 21,
    color = "black",
    size = 4
  ) +
  scale_x_datetime(
    date_breaks = "4 hours",
    date_labels = "%H",
    limits = c(ymd_hms("2022-11-27 6:00:00"),
               ymd_hms("2022-11-28 16:00:00"))
  ) +
  scale_shape_manual(values = c(21, 22)) +
  scale_color_manual(values = bb3.colors) +
  scale_fill_manual(values = bb3.colors, labels = scales::parse_format()) +
  labs(x =  "Hour",
       y = expression(bold("Gordon parameter"~italic((g)))),
       fill = expression(bold(Wavelength ~ (nm))),
       linetype = expression(bold(Experiment))) +
  facet_wrap(~ factor(phyto, levels = unique(optics_summary$phyto)),
              scales = "free_y",
              labeller = label_parsed) +
  # facet_wrap( ~ factor(phyto, levels = unique(optics_summary$phyto)),
  #             scales = "free_y",
  #             labeller = label_parsed) +
  guides(color = "none", fill = guide_legend(override.aes = list(shape = 21))) +
  theme_linedraw(21) +
  custom.theme 

g
```






