---
title: "Growth Rates"
author: "Nicholas Baetge"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
output: github_document
---

```{r chunk wrapper, include = FALSE}
knitr::knit_hooks$set(
  wrapper = function(before, options) {
    # the original chunk might be indented
    if (is.null(indent <- options$indent))
      indent <- ''
    
    # hide the wrapper=TRUE option
    opts <- gsub(', wrapper=TRUE', '', options$params.src)
    
    if (before) {
      # add the header
      sprintf('\n\n%s````\n```{r,%s}\n````\n', indent, opts)
    } else {
      # add the footer
      sprintf('\n\n%s````\n```\n````\n', indent)
    }
  }
)
```

- 

```{r load packages, message=FALSE, warning=FALSE, wrapper = TRUE}
library(tidyverse)
library(lubridate)
library(hms)
```

#############

# IMPORT & WRANGLE DATA

############## 

- 

```{r import, message=FALSE, warning=FALSE, wrapper=TRUE}
data <-  "cultures.xlsx" %>% 
  readxl::excel_sheets() %>% 
  set_names() %>% 
  map_dfr(readxl::read_excel, path = "cultures.xlsx") %>% 
  mutate(datetime = ymd_hms(paste(date, time)), .after = phyto) %>% 
  select(-date, -time)
```

```{r import lookup table for division rates, message=FALSE, warning=FALSE, wrapper=TRUE}
lookup <- readxl::read_excel("growth_rate_lookup.xlsx") %>% 
  rename(mu = mew_d)
```

-

#############

# CALCULATE GROWTH RATES

############## 

Here we calculate growth rates as the average daily growth rate from cell abundances (except for TP22-13 and TP22-14, which were run in turbidostat mode), from the night time decrease in FSC, and from dilution volume (for TP22-13 and TP22-14).

```{r calculate growthrates, message=FALSE, warning=FALSE, wrapper=TRUE}
gr <- data %>%
  group_by(phyto, bottle, cycle) %>%
  mutate(
    interv = interval(lag(datetime), datetime),
    duration = as.numeric(interv),
    interv_h = duration / 3600,
    interv_d = as.numeric(interv_h) / 24,
    log_cells = log10(mean_cells_ml),
    mu = ((log_cells - lag(log_cells)) * 2.303) / interv_d) %>% 
  ungroup()
```

-

```{r summarize, message=FALSE, warning=FALSE, wrapper=TRUE}
summary <- gr %>% 
  select(phyto, mu) %>% 
  drop_na(mu) %>% 
  group_by(phyto) %>% 
   summarize(across(
    .cols = mu,
    .fns = list(med = median, mean = mean, sd = sd, count = ~n()),
    # .fns = list(mean = mean, sd = sd),
    na.rm = TRUE,
    .names = "{fn}_{col}"
  ))  

summary
```
-

```{r refer to lookup, message=FALSE, warning=FALSE, wrapper=TRUE}
mean_mu <- summary %>% 
  select(phyto, mean_mu) %>% 
  rename(mu = mean_mu) %>% 
  mutate(mu = round(mu, 2)) 


divisions <- lookup %>% 
  add_row(mu = c(mean_mu$mu)) %>% 
  arrange(mu) %>% 
  mutate(divisions_d = zoo::na.approx(divisions_d, mu),
         doubling_d = zoo::na.approx(doubling_d, mu)) %>% 
  distinct() %>% 
  left_join(mean_mu, .) %>% 
  left_join(., summary %>% select(phyto, count_mu)) %>% 
  mutate(divisions = divisions_d * count_mu)

divisions
```








